### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by culmat** [mjeanroy/exiftool#139]
There are breaking changes between minor versions in 2.x.
I suggest upgrading the major version on each breaking change, see https://semver.org/

**Comment by mjeanroy** [comment]
Hi @culmat,

I'm sorry if some minor updates broke your build, that was not my intention: I always try to follow semantic versioning, and it looks like I missed some breaking changes in latest changes.

Sorry, I did not have a lot of time to actively maintain this lib in the past few months, but I'll be more careful 🙂

Since I agree with your suggestion (it was a mistake, not an intention to introduce breaking changes), I'm closing the issue, thank you for your feedbacks!
