### ISSUE TITLE
How to properly parse Keywords array?

### ISSUE THREAD

**Issue by sam** [mjeanroy/exiftool#6]
Given a photo with multiple Keywords:

```
$ exiftool -Keywords+="one, is good" sample.jpg
$ exiftool -Keywords+="two" sample.jpg
```

Running the following will show that Keywords is an Array:

```
$ exiftool -json -Keywords sample.jpg
[{
  "SourceFile": "sample.jpg",
  "Keywords": ["one, is good","two"]
}]
```

If you're using the regular output that `StayOpenStrategy` will use you'll get this however:

```
$ exiftool -Keywords sample.jpg
Keywords                        : one, is good, two
```

Which is just a String, meaning you can't get the correct "one, is good" entry.

You can pass a custom separator however:

```
exiftool -sep "☃" -Keywords sample.jpg
Keywords                        : one, is good☃two
```

Which you can then parse just fine.

I'm wondering if there's a way to do this with the current version of `exiftool-lib` (it doesn't appear so?), or if it'd require a modification. While passing arguments to `StayOpenStrategy` might be nice, this actually seems like a case that could just be hard-coded as long as the `-sep` value passed was reasonably unique like `|>☃` or something (it can/probably-should-be multiple characters).

And I suppose a corresponding change would be to make `StandardTag.IPTC_KEYWORDS` use a `Type.ARRAY` parser. Then the fact that there's a delimiter at all is completely transparent to the user.

Thoughts?

**Comment by mjeanroy** [comment]
Hi @sam,
Good catch, I did not know that you could parameterized the separator with `exiftool`.

Your proposition to use a "hard coded" separator seems nice. Of course, it would be better to allow user to override this separator, but this would complicate the API. For now, I think that a hard coded separator (as you said, as long as it is reasonably unique) should be enough.

For the parsing, you are right, a `Type.ARRAY` is the way to go. This is easy to implement however I am not sure if it might break some applications since the `parse` function for the `StandardTag.IPTC_KEYWORDS` will not return a string anymore but an array. What do you think?

**Comment by sam** [comment]
If it were me I'd probably just bump the minor version and note the breaking change in the README. If someone wants the old behavior they can `String.join(", ", values)`. In this case I think correctness is most important since right now there's no way (AFAIK) to get the correct behavior of multi-value fields.

There are actually quite a few "list" type tags: http://www.sno.phy.queensu.ca/~phil/exiftool/faq.html#Q17
